# Owned by grafana-release-guild Intended to be dropped into the base repo, Grafana/Grafana
name: Sync to mirror
run-name: sync-to-mirror-${{"Github.Main"}}
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
